# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AccountRecoveryupdatePassphraseContent(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, new_passphrase: str=None):  # noqa: E501
        """AccountRecoveryupdatePassphraseContent - a model defined in Swagger

        :param new_passphrase: The new_passphrase of this AccountRecoveryupdatePassphraseContent.  # noqa: E501
        :type new_passphrase: str
        """
        self.swagger_types = {
            'new_passphrase': str
        }

        self.attribute_map = {
            'new_passphrase': 'new-passphrase'
        }
        self._new_passphrase = new_passphrase

    @classmethod
    def from_dict(cls, dikt) -> 'AccountRecoveryupdatePassphraseContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The account_recoveryupdate_passphrase_content of this AccountRecoveryupdatePassphraseContent.  # noqa: E501
        :rtype: AccountRecoveryupdatePassphraseContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def new_passphrase(self) -> str:
        """Gets the new_passphrase of this AccountRecoveryupdatePassphraseContent.


        :return: The new_passphrase of this AccountRecoveryupdatePassphraseContent.
        :rtype: str
        """
        return self._new_passphrase

    @new_passphrase.setter
    def new_passphrase(self, new_passphrase: str):
        """Sets the new_passphrase of this AccountRecoveryupdatePassphraseContent.


        :param new_passphrase: The new_passphrase of this AccountRecoveryupdatePassphraseContent.
        :type new_passphrase: str
        """
        if new_passphrase is None:
            raise ValueError("Invalid value for `new_passphrase`, must not be `None`")  # noqa: E501

        self._new_passphrase = new_passphrase
