# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AccountRecoverysubmitCaptchaTokenContent(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, h_captcha_token: str=None):  # noqa: E501
        """AccountRecoverysubmitCaptchaTokenContent - a model defined in Swagger

        :param h_captcha_token: The h_captcha_token of this AccountRecoverysubmitCaptchaTokenContent.  # noqa: E501
        :type h_captcha_token: str
        """
        self.swagger_types = {
            'h_captcha_token': str
        }

        self.attribute_map = {
            'h_captcha_token': 'h-captcha-token'
        }
        self._h_captcha_token = h_captcha_token

    @classmethod
    def from_dict(cls, dikt) -> 'AccountRecoverysubmitCaptchaTokenContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The account_recoverysubmit_captcha_token_content of this AccountRecoverysubmitCaptchaTokenContent.  # noqa: E501
        :rtype: AccountRecoverysubmitCaptchaTokenContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def h_captcha_token(self) -> str:
        """Gets the h_captcha_token of this AccountRecoverysubmitCaptchaTokenContent.


        :return: The h_captcha_token of this AccountRecoverysubmitCaptchaTokenContent.
        :rtype: str
        """
        return self._h_captcha_token

    @h_captcha_token.setter
    def h_captcha_token(self, h_captcha_token: str):
        """Sets the h_captcha_token of this AccountRecoverysubmitCaptchaTokenContent.


        :param h_captcha_token: The h_captcha_token of this AccountRecoverysubmitCaptchaTokenContent.
        :type h_captcha_token: str
        """
        if h_captcha_token is None:
            raise ValueError("Invalid value for `h_captcha_token`, must not be `None`")  # noqa: E501

        self._h_captcha_token = h_captcha_token
