# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AccountRecoveryrequestPassphraseUpdateTokenContent(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, username: str=None):  # noqa: E501
        """AccountRecoveryrequestPassphraseUpdateTokenContent - a model defined in Swagger

        :param username: The username of this AccountRecoveryrequestPassphraseUpdateTokenContent.  # noqa: E501
        :type username: str
        """
        self.swagger_types = {
            'username': str
        }

        self.attribute_map = {
            'username': 'username'
        }
        self._username = username

    @classmethod
    def from_dict(cls, dikt) -> 'AccountRecoveryrequestPassphraseUpdateTokenContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The account_recoveryrequest_passphrase_update_token_content of this AccountRecoveryrequestPassphraseUpdateTokenContent.  # noqa: E501
        :rtype: AccountRecoveryrequestPassphraseUpdateTokenContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self) -> str:
        """Gets the username of this AccountRecoveryrequestPassphraseUpdateTokenContent.


        :return: The username of this AccountRecoveryrequestPassphraseUpdateTokenContent.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this AccountRecoveryrequestPassphraseUpdateTokenContent.


        :param username: The username of this AccountRecoveryrequestPassphraseUpdateTokenContent.
        :type username: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username
