# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CaptchaPrompt(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, show_captcha: bool=None):  # noqa: E501
        """CaptchaPrompt - a model defined in Swagger

        :param show_captcha: The show_captcha of this CaptchaPrompt.  # noqa: E501
        :type show_captcha: bool
        """
        self.swagger_types = {
            'show_captcha': bool
        }

        self.attribute_map = {
            'show_captcha': 'show-captcha'
        }
        self._show_captcha = show_captcha

    @classmethod
    def from_dict(cls, dikt) -> 'CaptchaPrompt':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CaptchaPrompt of this CaptchaPrompt.  # noqa: E501
        :rtype: CaptchaPrompt
        """
        return util.deserialize_model(dikt, cls)

    @property
    def show_captcha(self) -> bool:
        """Gets the show_captcha of this CaptchaPrompt.

        Whether or not the user must complete a captcha to continue authentication  # noqa: E501

        :return: The show_captcha of this CaptchaPrompt.
        :rtype: bool
        """
        return self._show_captcha

    @show_captcha.setter
    def show_captcha(self, show_captcha: bool):
        """Sets the show_captcha of this CaptchaPrompt.

        Whether or not the user must complete a captcha to continue authentication  # noqa: E501

        :param show_captcha: The show_captcha of this CaptchaPrompt.
        :type show_captcha: bool
        """
        if show_captcha is None:
            raise ValueError("Invalid value for `show_captcha`, must not be `None`")  # noqa: E501

        self._show_captcha = show_captcha
