# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DashboardInfoChildren(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, disabled: bool=None):  # noqa: E501
        """DashboardInfoChildren - a model defined in Swagger

        :param name: The name of this DashboardInfoChildren.  # noqa: E501
        :type name: str
        :param disabled: The disabled of this DashboardInfoChildren.  # noqa: E501
        :type disabled: bool
        """
        self.swagger_types = {
            'name': str,
            'disabled': bool
        }

        self.attribute_map = {
            'name': 'name',
            'disabled': 'disabled'
        }
        self._name = name
        self._disabled = disabled

    @classmethod
    def from_dict(cls, dikt) -> 'DashboardInfoChildren':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DashboardInfo_children of this DashboardInfoChildren.  # noqa: E501
        :rtype: DashboardInfoChildren
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this DashboardInfoChildren.


        :return: The name of this DashboardInfoChildren.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this DashboardInfoChildren.


        :param name: The name of this DashboardInfoChildren.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def disabled(self) -> bool:
        """Gets the disabled of this DashboardInfoChildren.


        :return: The disabled of this DashboardInfoChildren.
        :rtype: bool
        """
        return self._disabled

    @disabled.setter
    def disabled(self, disabled: bool):
        """Sets the disabled of this DashboardInfoChildren.


        :param disabled: The disabled of this DashboardInfoChildren.
        :type disabled: bool
        """
        if disabled is None:
            raise ValueError("Invalid value for `disabled`, must not be `None`")  # noqa: E501

        self._disabled = disabled
