# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.dashboard_info import DashboardInfo  # noqa: F401,E501

from swagger_server.models.account_info import AccountInfo  # noqa: F401,E501
from swagger_server.models.privacy_settings import PrivacySettings  # noqa: F401,E501
from swagger_server.models.route_category import RouteCategory  # noqa: F401,E501


from swagger_server.models.nonce_token import NonceToken  # noqa: F401,E501
from swagger_server import util


class DashboardInfoContainer(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, nonce: NonceToken=None, content: DashboardInfo=None):  # noqa: E501
        """DashboardInfoContainer - a model defined in Swagger

        :param nonce: The nonce of this DashboardInfoContainer.  # noqa: E501
        :type nonce: NonceToken
        :param content: The content of this DashboardInfoContainer.  # noqa: E501
        :type content: DashboardInfo
        """
        self.swagger_types = {
            'nonce': NonceToken,
            'content': DashboardInfo
        }

        self.attribute_map = {
            'nonce': 'nonce',
            'content': 'content'
        }
        self._nonce = nonce
        self._content = content

    @classmethod
    def from_dict(cls, dikt) -> 'DashboardInfoContainer':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DashboardInfoContainer of this DashboardInfoContainer.  # noqa: E501
        :rtype: DashboardInfoContainer
        """
        return util.deserialize_model(dikt, cls)

    @property
    def nonce(self) -> NonceToken:
        """Gets the nonce of this DashboardInfoContainer.


        :return: The nonce of this DashboardInfoContainer.
        :rtype: NonceToken
        """
        return self._nonce

    @nonce.setter
    def nonce(self, nonce: NonceToken):
        """Sets the nonce of this DashboardInfoContainer.


        :param nonce: The nonce of this DashboardInfoContainer.
        :type nonce: NonceToken
        """

        self._nonce = nonce

    @property
    def content(self) -> DashboardInfo:
        """Gets the content of this DashboardInfoContainer.


        :return: The content of this DashboardInfoContainer.
        :rtype: DashboardInfo
        """
        return self._content

    @content.setter
    def content(self, content: DashboardInfo):
        """Sets the content of this DashboardInfoContainer.


        :param content: The content of this DashboardInfoContainer.
        :type content: DashboardInfo
        """

        self._content = content
