# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DashboardgetUserInfoContent(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, account_token: str=None):  # noqa: E501
        """DashboardgetUserInfoContent - a model defined in Swagger

        :param account_token: The account_token of this DashboardgetUserInfoContent.  # noqa: E501
        :type account_token: str
        """
        self.swagger_types = {
            'account_token': str
        }

        self.attribute_map = {
            'account_token': 'account-token'
        }
        self._account_token = account_token

    @classmethod
    def from_dict(cls, dikt) -> 'DashboardgetUserInfoContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The dashboardget_user_info_content of this DashboardgetUserInfoContent.  # noqa: E501
        :rtype: DashboardgetUserInfoContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def account_token(self) -> str:
        """Gets the account_token of this DashboardgetUserInfoContent.


        :return: The account_token of this DashboardgetUserInfoContent.
        :rtype: str
        """
        return self._account_token

    @account_token.setter
    def account_token(self, account_token: str):
        """Sets the account_token of this DashboardgetUserInfoContent.


        :param account_token: The account_token of this DashboardgetUserInfoContent.
        :type account_token: str
        """

        self._account_token = account_token
