# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class FinishRegistration(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, verification_code: str=None, password: str=None, secret_question: str=None, secret_answer: str=None):  # noqa: E501
        """FinishRegistration - a model defined in Swagger

        :param verification_code: The verification_code of this FinishRegistration.  # noqa: E501
        :type verification_code: str
        :param password: The password of this FinishRegistration.  # noqa: E501
        :type password: str
        :param secret_question: The secret_question of this FinishRegistration.  # noqa: E501
        :type secret_question: str
        :param secret_answer: The secret_answer of this FinishRegistration.  # noqa: E501
        :type secret_answer: str
        """
        self.swagger_types = {
            'verification_code': str,
            'password': str,
            'secret_question': str,
            'secret_answer': str
        }

        self.attribute_map = {
            'verification_code': 'verification-code',
            'password': 'password',
            'secret_question': 'secret-question',
            'secret_answer': 'secret-answer'
        }
        self._verification_code = verification_code
        self._password = password
        self._secret_question = secret_question
        self._secret_answer = secret_answer

    @classmethod
    def from_dict(cls, dikt) -> 'FinishRegistration':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FinishRegistration of this FinishRegistration.  # noqa: E501
        :rtype: FinishRegistration
        """
        return util.deserialize_model(dikt, cls)

    @property
    def verification_code(self) -> str:
        """Gets the verification_code of this FinishRegistration.

        The token the user previously received via the verification email  # noqa: E501

        :return: The verification_code of this FinishRegistration.
        :rtype: str
        """
        return self._verification_code

    @verification_code.setter
    def verification_code(self, verification_code: str):
        """Sets the verification_code of this FinishRegistration.

        The token the user previously received via the verification email  # noqa: E501

        :param verification_code: The verification_code of this FinishRegistration.
        :type verification_code: str
        """
        if verification_code is None:
            raise ValueError("Invalid value for `verification_code`, must not be `None`")  # noqa: E501

        self._verification_code = verification_code

    @property
    def password(self) -> str:
        """Gets the password of this FinishRegistration.

        The account password  # noqa: E501

        :return: The password of this FinishRegistration.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this FinishRegistration.

        The account password  # noqa: E501

        :param password: The password of this FinishRegistration.
        :type password: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    @property
    def secret_question(self) -> str:
        """Gets the secret_question of this FinishRegistration.

        A question which the user can answer to recover the account in case they ever forget their password or lose their MFA device  # noqa: E501

        :return: The secret_question of this FinishRegistration.
        :rtype: str
        """
        return self._secret_question

    @secret_question.setter
    def secret_question(self, secret_question: str):
        """Sets the secret_question of this FinishRegistration.

        A question which the user can answer to recover the account in case they ever forget their password or lose their MFA device  # noqa: E501

        :param secret_question: The secret_question of this FinishRegistration.
        :type secret_question: str
        """

        self._secret_question = secret_question

    @property
    def secret_answer(self) -> str:
        """Gets the secret_answer of this FinishRegistration.

        The answer to the secret question.  # noqa: E501

        :return: The secret_answer of this FinishRegistration.
        :rtype: str
        """
        return self._secret_answer

    @secret_answer.setter
    def secret_answer(self, secret_answer: str):
        """Sets the secret_answer of this FinishRegistration.

        The answer to the secret question.  # noqa: E501

        :param secret_answer: The secret_answer of this FinishRegistration.
        :type secret_answer: str
        """

        self._secret_answer = secret_answer
