# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.next_frame import NextFrame  # noqa: F401,E501
from swagger_server.models.nonce_token import NonceToken  # noqa: F401,E501
from swagger_server import util


class InitializedSession(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, nonce: NonceToken=None, content: NextFrame=None):  # noqa: E501
        """InitializedSession - a model defined in Swagger

        :param nonce: The nonce of this InitializedSession.  # noqa: E501
        :type nonce: NonceToken
        :param content: The content of this InitializedSession.  # noqa: E501
        :type content: NextFrame
        """
        self.swagger_types = {
            'nonce': NonceToken,
            'content': NextFrame
        }

        self.attribute_map = {
            'nonce': 'nonce',
            'content': 'content'
        }
        self._nonce = nonce
        self._content = content

    @classmethod
    def from_dict(cls, dikt) -> 'InitializedSession':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InitializedSession of this InitializedSession.  # noqa: E501
        :rtype: InitializedSession
        """
        return util.deserialize_model(dikt, cls)

    @property
    def nonce(self) -> NonceToken:
        """Gets the nonce of this InitializedSession.


        :return: The nonce of this InitializedSession.
        :rtype: NonceToken
        """
        return self._nonce

    @nonce.setter
    def nonce(self, nonce: NonceToken):
        """Sets the nonce of this InitializedSession.


        :param nonce: The nonce of this InitializedSession.
        :type nonce: NonceToken
        """

        self._nonce = nonce

    @property
    def content(self) -> NextFrame:
        """Gets the content of this InitializedSession.


        :return: The content of this InitializedSession.
        :rtype: NextFrame
        """
        return self._content

    @content.setter
    def content(self, content: NextFrame):
        """Sets the content of this InitializedSession.


        :param content: The content of this InitializedSession.
        :type content: NextFrame
        """

        self._content = content
