# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IsInitialCaptchaRequiredContent(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, captcha_required: bool=None):  # noqa: E501
        """IsInitialCaptchaRequiredContent - a model defined in Swagger

        :param captcha_required: The captcha_required of this IsInitialCaptchaRequiredContent.  # noqa: E501
        :type captcha_required: bool
        """
        self.swagger_types = {
            'captcha_required': bool
        }

        self.attribute_map = {
            'captcha_required': 'captcha-required'
        }
        self._captcha_required = captcha_required

    @classmethod
    def from_dict(cls, dikt) -> 'IsInitialCaptchaRequiredContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The IsInitialCaptchaRequired_content of this IsInitialCaptchaRequiredContent.  # noqa: E501
        :rtype: IsInitialCaptchaRequiredContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def captcha_required(self) -> bool:
        """Gets the captcha_required of this IsInitialCaptchaRequiredContent.


        :return: The captcha_required of this IsInitialCaptchaRequiredContent.
        :rtype: bool
        """
        return self._captcha_required

    @captcha_required.setter
    def captcha_required(self, captcha_required: bool):
        """Sets the captcha_required of this IsInitialCaptchaRequiredContent.


        :param captcha_required: The captcha_required of this IsInitialCaptchaRequiredContent.
        :type captcha_required: bool
        """
        if captcha_required is None:
            raise ValueError("Invalid value for `captcha_required`, must not be `None`")  # noqa: E501

        self._captcha_required = captcha_required
