# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LinkedAccount(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, href: str=None):  # noqa: E501
        """LinkedAccount - a model defined in Swagger

        :param name: The name of this LinkedAccount.  # noqa: E501
        :type name: str
        :param href: The href of this LinkedAccount.  # noqa: E501
        :type href: str
        """
        self.swagger_types = {
            'name': str,
            'href': str
        }

        self.attribute_map = {
            'name': 'name',
            'href': 'href'
        }
        self._name = name
        self._href = href

    @classmethod
    def from_dict(cls, dikt) -> 'LinkedAccount':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LinkedAccount of this LinkedAccount.  # noqa: E501
        :rtype: LinkedAccount
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this LinkedAccount.


        :return: The name of this LinkedAccount.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this LinkedAccount.


        :param name: The name of this LinkedAccount.
        :type name: str
        """

        self._name = name

    @property
    def href(self) -> str:
        """Gets the href of this LinkedAccount.


        :return: The href of this LinkedAccount.
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href: str):
        """Sets the href of this LinkedAccount.


        :param href: The href of this LinkedAccount.
        :type href: str
        """

        self._href = href
