# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.loginsubmit_frame_content import LoginsubmitFrameContent  # noqa: F401,E501
from swagger_server.models.nonce_token import NonceToken  # noqa: F401,E501
from swagger_server import util


class LoginSubmitFrameBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, nonce: NonceToken=None, content: LoginsubmitFrameContent=None):  # noqa: E501
        """LoginSubmitFrameBody - a model defined in Swagger

        :param nonce: The nonce of this LoginSubmitFrameBody.  # noqa: E501
        :type nonce: NonceToken
        :param content: The content of this LoginSubmitFrameBody.  # noqa: E501
        :type content: LoginsubmitFrameContent
        """
        self.swagger_types = {
            'nonce': NonceToken,
            'content': LoginsubmitFrameContent
        }

        self.attribute_map = {
            'nonce': 'nonce',
            'content': 'content'
        }
        self._nonce = nonce
        self._content = content

    @classmethod
    def from_dict(cls, dikt) -> 'LoginSubmitFrameBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The login_submit_frame_body of this LoginSubmitFrameBody.  # noqa: E501
        :rtype: LoginSubmitFrameBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def nonce(self) -> NonceToken:
        """Gets the nonce of this LoginSubmitFrameBody.


        :return: The nonce of this LoginSubmitFrameBody.
        :rtype: NonceToken
        """
        return self._nonce

    @nonce.setter
    def nonce(self, nonce: NonceToken):
        """Sets the nonce of this LoginSubmitFrameBody.


        :param nonce: The nonce of this LoginSubmitFrameBody.
        :type nonce: NonceToken
        """

        self._nonce = nonce

    @property
    def content(self) -> LoginsubmitFrameContent:
        """Gets the content of this LoginSubmitFrameBody.


        :return: The content of this LoginSubmitFrameBody.
        :rtype: LoginsubmitFrameContent
        """
        return self._content

    @content.setter
    def content(self, content: LoginsubmitFrameContent):
        """Sets the content of this LoginSubmitFrameBody.


        :param content: The content of this LoginSubmitFrameBody.
        :type content: LoginsubmitFrameContent
        """

        self._content = content
