# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class NonceToken3Content(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, secret_question: str=None):  # noqa: E501
        """NonceToken3Content - a model defined in Swagger

        :param secret_question: The secret_question of this NonceToken3Content.  # noqa: E501
        :type secret_question: str
        """
        self.swagger_types = {
            'secret_question': str
        }

        self.attribute_map = {
            'secret_question': 'secret-question'
        }
        self._secret_question = secret_question

    @classmethod
    def from_dict(cls, dikt) -> 'NonceToken3Content':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NonceToken_3_content of this NonceToken3Content.  # noqa: E501
        :rtype: NonceToken3Content
        """
        return util.deserialize_model(dikt, cls)

    @property
    def secret_question(self) -> str:
        """Gets the secret_question of this NonceToken3Content.


        :return: The secret_question of this NonceToken3Content.
        :rtype: str
        """
        return self._secret_question

    @secret_question.setter
    def secret_question(self, secret_question: str):
        """Sets the secret_question of this NonceToken3Content.


        :param secret_question: The secret_question of this NonceToken3Content.
        :type secret_question: str
        """

        self._secret_question = secret_question
