# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class NonceToken2(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, nonce: str=None):  # noqa: E501
        """NonceToken2 - a model defined in Swagger

        :param nonce: The nonce of this NonceToken2.  # noqa: E501
        :type nonce: str
        """
        self.swagger_types = {
            'nonce': str
        }

        self.attribute_map = {
            'nonce': 'nonce'
        }
        self._nonce = nonce

    @classmethod
    def from_dict(cls, dikt) -> 'NonceToken2':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NonceToken_2 of this NonceToken2.  # noqa: E501
        :rtype: NonceToken2
        """
        return util.deserialize_model(dikt, cls)

    @property
    def nonce(self) -> str:
        """Gets the nonce of this NonceToken2.


        :return: The nonce of this NonceToken2.
        :rtype: str
        """
        return self._nonce

    @nonce.setter
    def nonce(self, nonce: str):
        """Sets the nonce of this NonceToken2.


        :param nonce: The nonce of this NonceToken2.
        :type nonce: str
        """

        self._nonce = nonce
