# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.nonce_token import NonceToken  # noqa: F401,E501
from swagger_server.models.registerresend_verification_mail_content import RegisterresendVerificationMailContent  # noqa: F401,E501
from swagger_server import util


class ResendVerificationMail1(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, nonce: NonceToken=None, content: RegisterresendVerificationMailContent=None):  # noqa: E501
        """ResendVerificationMail1 - a model defined in Swagger

        :param nonce: The nonce of this ResendVerificationMail1.  # noqa: E501
        :type nonce: NonceToken
        :param content: The content of this ResendVerificationMail1.  # noqa: E501
        :type content: RegisterresendVerificationMailContent
        """
        self.swagger_types = {
            'nonce': NonceToken,
            'content': RegisterresendVerificationMailContent
        }

        self.attribute_map = {
            'nonce': 'nonce',
            'content': 'content'
        }
        self._nonce = nonce
        self._content = content

    @classmethod
    def from_dict(cls, dikt) -> 'ResendVerificationMail1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResendVerificationMail_1 of this ResendVerificationMail1.  # noqa: E501
        :rtype: ResendVerificationMail1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def nonce(self) -> NonceToken:
        """Gets the nonce of this ResendVerificationMail1.


        :return: The nonce of this ResendVerificationMail1.
        :rtype: NonceToken
        """
        return self._nonce

    @nonce.setter
    def nonce(self, nonce: NonceToken):
        """Sets the nonce of this ResendVerificationMail1.


        :param nonce: The nonce of this ResendVerificationMail1.
        :type nonce: NonceToken
        """
        if nonce is None:
            raise ValueError("Invalid value for `nonce`, must not be `None`")  # noqa: E501

        self._nonce = nonce

    @property
    def content(self) -> RegisterresendVerificationMailContent:
        """Gets the content of this ResendVerificationMail1.


        :return: The content of this ResendVerificationMail1.
        :rtype: RegisterresendVerificationMailContent
        """
        return self._content

    @content.setter
    def content(self, content: RegisterresendVerificationMailContent):
        """Sets the content of this ResendVerificationMail1.


        :param content: The content of this ResendVerificationMail1.
        :type content: RegisterresendVerificationMailContent
        """
        if content is None:
            raise ValueError("Invalid value for `content`, must not be `None`")  # noqa: E501

        self._content = content
