# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SuccessfulAuthentication(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, redirect: str=None, token: str=None):  # noqa: E501
        """SuccessfulAuthentication - a model defined in Swagger

        :param redirect: The redirect of this SuccessfulAuthentication.  # noqa: E501
        :type redirect: str
        :param token: The token of this SuccessfulAuthentication.  # noqa: E501
        :type token: str
        """
        self.swagger_types = {
            'redirect': str,
            'token': str
        }

        self.attribute_map = {
            'redirect': 'redirect',
            'token': 'token'
        }
        self._redirect = redirect
        self._token = token

    @classmethod
    def from_dict(cls, dikt) -> 'SuccessfulAuthentication':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SuccessfulAuthentication of this SuccessfulAuthentication.  # noqa: E501
        :rtype: SuccessfulAuthentication
        """
        return util.deserialize_model(dikt, cls)

    @property
    def redirect(self) -> str:
        """Gets the redirect of this SuccessfulAuthentication.

        The client should visit this domain next  # noqa: E501

        :return: The redirect of this SuccessfulAuthentication.
        :rtype: str
        """
        return self._redirect

    @redirect.setter
    def redirect(self, redirect: str):
        """Sets the redirect of this SuccessfulAuthentication.

        The client should visit this domain next  # noqa: E501

        :param redirect: The redirect of this SuccessfulAuthentication.
        :type redirect: str
        """
        if redirect is None:
            raise ValueError("Invalid value for `redirect`, must not be `None`")  # noqa: E501

        self._redirect = redirect

    @property
    def token(self) -> str:
        """Gets the token of this SuccessfulAuthentication.

        A cookie that will prove account ownership to HTS apps  # noqa: E501

        :return: The token of this SuccessfulAuthentication.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token: str):
        """Sets the token of this SuccessfulAuthentication.

        A cookie that will prove account ownership to HTS apps  # noqa: E501

        :param token: The token of this SuccessfulAuthentication.
        :type token: str
        """
        if token is None:
            raise ValueError("Invalid value for `token`, must not be `None`")  # noqa: E501

        self._token = token
